[2019-12-10T06:17:30.322230+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:17:31.337971+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6058a3"},"request_uri":"http://symfony.localhost/_wdt/6058a3","method":"GET"} []
[2019-12-10T06:17:31.769405+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://symfony.localhost/")" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://symfony.localhost/\") at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-12-10T06:32:49.942318+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:32:50.776107+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"996ff9"},"request_uri":"http://symfony.localhost/_wdt/996ff9","method":"GET"} []
[2019-12-10T06:33:15.827426+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:33:16.362248+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"bc6fd7"},"request_uri":"http://symfony.localhost/_wdt/bc6fd7","method":"GET"} []
[2019-12-10T06:34:22.728346+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:34:23.273811+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2d717a"},"request_uri":"http://symfony.localhost/_wdt/2d717a","method":"GET"} []
[2019-12-10T06:34:45.859789+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /symfony-test-v1.0"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /symfony-test-v1.0\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/symfony-test-v1.0/\". at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-12-10T06:34:46.888296+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5433be"},"request_uri":"http://symfony.localhost/_wdt/5433be","method":"GET"} []
[2019-12-10T06:35:05.396118+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:35:05.862274+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2c3036"},"request_uri":"http://symfony.localhost/_wdt/2c3036","method":"GET"} []
[2019-12-10T06:38:23.344883+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:38:23.820657+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ddc236"},"request_uri":"http://symfony.localhost/_wdt/ddc236","method":"GET"} []
[2019-12-10T06:38:46.037627+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:38:46.488925+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4667ff"},"request_uri":"http://symfony.localhost/_wdt/4667ff","method":"GET"} []
[2019-12-10T06:41:57.575838+00:00] console.ERROR: Error thrown while running command "'server:run'". Message: "Command "server:run" is not defined.  Did you mean this?     server:dump" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"server:run\" is not defined.\n\nDid you mean this?\n    server:dump at /var/www/symfony/vendor/symfony/console/Application.php:645)","command":"'server:run'","message":"Command \"server:run\" is not defined.\n\nDid you mean this?\n    server:dump"} []
[2019-12-10T06:43:10.479287+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T06:43:10.825453+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T06:43:11.309040+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"587e8e"},"request_uri":"http://symfony.localhost/_wdt/587e8e","method":"GET"} []
[2019-12-10T06:44:17.443782+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T06:44:18.040707+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T06:44:18.953929+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a36aaa"},"request_uri":"http://symfony.localhost/_wdt/a36aaa","method":"GET"} []
[2019-12-10T06:44:21.472890+00:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"http://symfony.localhost/_profiler/open?file=src%2FController%2FDefaultController.php&line=0","method":"GET"} []
[2019-12-10T06:44:25.880341+00:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"http://symfony.localhost/_profiler/open?file=templates%2Fdefault%2Findex.html.twig&line=0","method":"GET"} []
[2019-12-10T06:44:31.531422+00:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"http://symfony.localhost/_profiler/open?file=src%2FController%2FDefaultController.php&line=0","method":"GET"} []
[2019-12-10T06:44:44.565339+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:44:45.115886+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"658944"},"request_uri":"http://symfony.localhost/_wdt/658944","method":"GET"} []
[2019-12-10T06:52:49.429062+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:52:50.329355+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f1a398"},"request_uri":"http://symfony.localhost/_wdt/f1a398","method":"GET"} []
[2019-12-10T06:54:55.308967+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T06:54:55.942541+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"fca14c"},"request_uri":"http://symfony.localhost/_wdt/fca14c","method":"GET"} []
[2019-12-10T06:54:59.688575+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T06:54:59.919685+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T06:55:00.327358+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"529fb6"},"request_uri":"http://symfony.localhost/_wdt/529fb6","method":"GET"} []
[2019-12-10T06:56:06.804396+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T06:56:06.954955+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T06:56:07.438173+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1a612b"},"request_uri":"http://symfony.localhost/_wdt/1a612b","method":"GET"} []
[2019-12-10T07:36:48.354268+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T07:36:48.892079+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T07:36:49.474533+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cf4b57"},"request_uri":"http://symfony.localhost/_wdt/cf4b57","method":"GET"} []
[2019-12-10T07:37:09.801960+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T07:37:10.522288+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"902fc9"},"request_uri":"http://symfony.localhost/_wdt/902fc9","method":"GET"} []
[2019-12-10T07:37:35.307034+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T07:37:35.866234+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"cf054b"},"request_uri":"http://symfony.localhost/_wdt/cf054b","method":"GET"} []
[2019-12-10T07:37:47.585361+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T07:37:47.728543+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T07:37:48.138677+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d42aab"},"request_uri":"http://symfony.localhost/_wdt/d42aab","method":"GET"} []
[2019-12-10T07:43:43.724815+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T07:43:44.312410+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T07:43:44.924704+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2452a1"},"request_uri":"http://symfony.localhost/_wdt/2452a1","method":"GET"} []
[2019-12-10T11:08:38.063413+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2019-12-10T11:08:38.942877+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6773c2"},"request_uri":"http://symfony.localhost/_wdt/6773c2","method":"GET"} []
[2019-12-10T11:08:46.498415+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:08:46.776687+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:08:47.410960+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:08:48.302123+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e1ef02"},"request_uri":"http://symfony.localhost/_wdt/e1ef02","method":"GET"} []
[2019-12-10T11:09:42.359035+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Syntax Error] Expected PlainValue, got ''' at position 48 in method App\Controller\KitapController::index() in /var/www/symfony/config/routes/../../src/Controller/ (which is being imported from "/var/www/symfony/config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php line 173 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Syntax Error] Expected PlainValue, got ''' at position 48 in method App\\Controller\\KitapController::index() in /var/www/symfony/config/routes/../../src/Controller/ (which is being imported from \"/var/www/symfony/config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at /var/www/symfony/vendor/symfony/config/Loader/FileLoader.php:173)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Syntax Error] Expected PlainValue, got ''' at position 48 in method App\\Controller\\KitapController::index(). at /var/www/symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:42)"} []
[2019-12-10T11:11:42.635491+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:11:42.753364+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "merhaba.html.twig" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"merhaba.html.twig\" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2019-12-10T11:11:43.211547+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:11:44.240113+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4aadf9"},"request_uri":"http://symfony.localhost/_wdt/4aadf9","method":"GET"} []
[2019-12-10T11:13:41.562378+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:13:41.670830+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "kitap/merhaba.html.twig" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"kitap/merhaba.html.twig\" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2019-12-10T11:13:42.100399+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:13:43.145141+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"7c9290"},"request_uri":"http://symfony.localhost/_wdt/7c9290","method":"GET"} []
[2019-12-10T11:15:59.652038+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:15:59.785277+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:16:00.289042+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:16:01.424709+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4b4ba4"},"request_uri":"http://symfony.localhost/_wdt/4b4ba4","method":"GET"} []
[2019-12-10T11:16:23.812738+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:16:23.964130+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:16:24.589009+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:16:27.581765+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:16:27.703272+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:16:28.220757+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:16:29.104192+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e8e732"},"request_uri":"http://symfony.localhost/_wdt/e8e732","method":"GET"} []
[2019-12-10T11:16:40.661934+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:16:40.802218+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:16:41.360258+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:16:42.340818+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b05e53"},"request_uri":"http://symfony.localhost/_wdt/b05e53","method":"GET"} []
[2019-12-10T11:17:17.141944+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:17:17.277045+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:17:17.813412+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:17:34.241335+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:17:34.393093+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "controller_name" does not exist." at /var/www/symfony/templates/kitap/index.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"controller_name\" does not exist. at /var/www/symfony/templates/kitap/index.html.twig:12)"} []
[2019-12-10T11:17:34.970205+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:17:35.890879+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"0a8880"},"request_uri":"http://symfony.localhost/_wdt/0a8880","method":"GET"} []
[2019-12-10T11:17:51.766093+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T11:17:52.039193+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:17:53.019239+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"077d72"},"request_uri":"http://symfony.localhost/_wdt/077d72","method":"GET"} []
[2019-12-10T11:18:47.172751+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T11:18:47.302383+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:18:47.671395+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:18:48.018917+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:18:48.967550+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"1cba41"},"request_uri":"http://symfony.localhost/_wdt/1cba41","method":"GET"} []
[2019-12-10T11:18:58.939887+00:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"http://symfony.localhost/_profiler/open?file=src%2FController%2FKitapController.php&line=0","method":"GET"} []
[2019-12-10T11:19:04.451628+00:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"http://symfony.localhost/_profiler/open?file=templates%2Fkitap%2Findex.html.twig&line=0","method":"GET"} []
[2019-12-10T11:19:40.759463+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:19:40.870710+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "kitap/merhaba.html.twig" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"kitap/merhaba.html.twig\" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2019-12-10T11:19:41.207134+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:19:42.072682+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"46e9eb"},"request_uri":"http://symfony.localhost/_wdt/46e9eb","method":"GET"} []
[2019-12-10T11:19:57.893549+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:19:57.992617+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "kitap/merhaba.html.twig" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"kitap/merhaba.html.twig\" (looked into: /var/www/symfony/templates, /var/www/symfony/vendor/symfony/twig-bridge/Resources/views/Form). at /var/www/symfony/vendor/twig/twig/src/Loader/FilesystemLoader.php:227)"} []
[2019-12-10T11:19:58.436495+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:19:59.319916+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3119ff"},"request_uri":"http://symfony.localhost/_wdt/3119ff","method":"GET"} []
[2019-12-10T11:20:58.003729+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/kitap","method":"GET"} []
[2019-12-10T11:20:58.260951+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:20:59.106653+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ebeb0a"},"request_uri":"http://symfony.localhost/_wdt/ebeb0a","method":"GET"} []
[2019-12-10T11:21:36.285897+00:00] request.INFO: Matched route "kitap". {"route":"kitap","route_parameters":{"_route":"kitap","_controller":"App\\Controller\\KitapController::index"},"request_uri":"http://symfony.localhost/","method":"GET"} []
[2019-12-10T11:21:36.415815+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:21:37.184031+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"5f2afa"},"request_uri":"http://symfony.localhost/_wdt/5f2afa","method":"GET"} []
[2019-12-10T11:23:14.243691+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T11:23:14.336005+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: "The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned a number (7)." at /var/www/symfony/src/Controller/KitapController.php line 24 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned a number (7). at /var/www/symfony/src/Controller/KitapController.php:24)"} []
[2019-12-10T11:23:14.574127+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:23:15.282156+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"bba604"},"request_uri":"http://symfony.localhost/_wdt/bba604","method":"GET"} []
[2019-12-10T11:24:03.873914+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T11:24:03.991126+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: "The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned a string ("8")." at /var/www/symfony/src/Controller/KitapController.php line 24 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned a string (\"8\"). at /var/www/symfony/src/Controller/KitapController.php:24)"} []
[2019-12-10T11:24:04.266207+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:24:05.079420+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"dd5fc5"},"request_uri":"http://symfony.localhost/_wdt/dd5fc5","method":"GET"} []
[2019-12-10T11:24:31.025670+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T11:24:31.122414+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: "The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned an array ([0 => ...])." at /var/www/symfony/src/Controller/KitapController.php line 24 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\ControllerDoesNotReturnResponseException(code: 0): The controller must return a \"Symfony\\Component\\HttpFoundation\\Response\" object but it returned an array ([0 => ...]). at /var/www/symfony/src/Controller/KitapController.php:24)"} []
[2019-12-10T11:24:31.374290+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:24:32.199155+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"68c236"},"request_uri":"http://symfony.localhost/_wdt/68c236","method":"GET"} []
[2019-12-10T11:26:12.488222+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T11:26:12.552803+00:00] php.CRITICAL: Uncaught Error: Call to undefined function App\Controller\JsonResponse() {"exception":"[object] (Error(code: 0): Call to undefined function App\\Controller\\JsonResponse() at /var/www/symfony/src/Controller/KitapController.php:23)"} []
[2019-12-10T11:26:12.638500+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedFunctionError: "Attempted to call function "JsonResponse" from namespace "App\Controller"." at /var/www/symfony/src/Controller/KitapController.php line 23 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedFunctionError(code: 0): Attempted to call function \"JsonResponse\" from namespace \"App\\Controller\". at /var/www/symfony/src/Controller/KitapController.php:23)"} []
[2019-12-10T11:26:12.892754+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:26:13.926619+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"81873f"},"request_uri":"http://symfony.localhost/_wdt/81873f","method":"GET"} []
[2019-12-10T11:27:42.708638+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T11:27:42.880252+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T11:53:42.008328+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T11:53:42.028959+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:09:03.648025+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T12:09:03.671145+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:13:29.577032+00:00] request.INFO: Matched route "kitapListesi". {"route":"kitapListesi","route_parameters":{"_route":"kitapListesi","_controller":"App\\Controller\\KitapController::kitapListesi"},"request_uri":"http://symfony.localhost/kitapListesi","method":"GET"} []
[2019-12-10T12:13:30.560690+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T12:15:02.530229+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T12:15:02.554295+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:20:31.403672+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T12:20:31.436560+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:21:11.156947+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T12:21:11.182064+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:28:12.968599+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused"} []
[2019-12-10T12:28:12.990944+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:52:24.546477+00:00] console.ERROR: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Try again at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:database:create","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Try again"} []
[2019-12-10T12:52:24.570136+00:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2019-12-10T12:58:19.723275+00:00] console.ERROR: Error thrown while running command "make:entity". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:entity","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve"} []
[2019-12-10T12:58:19.754007+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2019-12-10T13:01:38.956256+00:00] console.ERROR: Error thrown while running command "make:entity". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"make:entity","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve"} []
[2019-12-10T13:01:38.981979+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2019-12-10T13:04:38.403350+00:00] console.ERROR: Error thrown while running command "doctrine:schema:update". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does not resolve at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:schema:update","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name does not resolve"} []
[2019-12-10T13:04:38.424736+00:00] console.DEBUG: Command "doctrine:schema:update" exited with code "1" {"command":"doctrine:schema:update","code":1} []
[2019-12-10T13:05:09.480810+00:00] console.ERROR: Error thrown while running command "doctrine:schema:update". Message: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.27.0.3' (using password: YES)" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.27.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:93)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.27.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.27.0.3' (using password: YES) at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)","command":"doctrine:schema:update","message":"An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.27.0.3' (using password: YES)"} []
[2019-12-10T13:05:09.501790+00:00] console.DEBUG: Command "doctrine:schema:update" exited with code "1" {"command":"doctrine:schema:update","code":1} []
[2019-12-10T13:06:06.335314+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:06:06.506198+00:00] console.DEBUG: Command "doctrine:schema:update" exited with code "1" {"command":"doctrine:schema:update","code":1} []
[2019-12-10T13:06:14.635536+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:06:37.500645+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:06:37.630884+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:06:37.642514+00:00] doctrine.DEBUG: CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, surname VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:07:29.643205+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:07:29.661212+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:07:29.696738+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:07:29.705618+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:07:29.737060+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:07:29.798916+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:07:29.808572+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:07:29.814808+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:07:29.820818+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:07:29.825644+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:07:29.840992+00:00] doctrine.DEBUG: ALTER TABLE user ADD phone INT DEFAULT NULL [] []
[2019-12-10T13:09:36.615178+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:09:36.633142+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:09:36.671340+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:09:36.678213+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:09:36.708725+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:09:36.772963+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:09:36.782143+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:09:36.792778+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:09:36.799610+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:09:36.804511+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:09:36.821976+00:00] doctrine.DEBUG: CREATE TABLE `group` (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:11:26.134936+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:11:26.154340+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:11:26.191013+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:11:26.197267+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:11:26.231325+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:11:26.239207+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:11:26.246414+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:11:26.251872+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:11:26.257072+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:11:26.346157+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:11:26.355129+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:11:26.363443+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:11:26.368921+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:11:26.378521+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:11:26.382899+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:11:26.389830+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:11:26.395190+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:11:26.400427+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:11:26.425352+00:00] doctrine.DEBUG: ALTER TABLE `group` ADD user_id INT DEFAULT NULL [] []
[2019-12-10T13:11:26.445400+00:00] doctrine.DEBUG: ALTER TABLE `group` ADD CONSTRAINT FK_6DC044C5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) [] []
[2019-12-10T13:11:26.495021+00:00] doctrine.DEBUG: CREATE INDEX IDX_6DC044C5A76ED395 ON `group` (user_id) [] []
[2019-12-10T13:12:44.860580+00:00] console.ERROR: Error thrown while running command "make:entity". Message: "Cannot find file "/var/www/symfony/src/Entity/User.php"" {"exception":"[object] (InvalidArgumentException(code: 0): Cannot find file \"/var/www/symfony/src/Entity/User.php\" at /var/www/symfony/vendor/symfony/maker-bundle/src/FileManager.php:117)","command":"make:entity","message":"Cannot find file \"/var/www/symfony/src/Entity/User.php\""} []
[2019-12-10T13:12:44.884595+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2019-12-10T13:12:52.058186+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2019-12-10T13:13:11.791786+00:00] console.DEBUG: Command "make:entity" exited with code "1" {"command":"make:entity","code":1} []
[2019-12-10T13:16:12.131172+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:16:12.150079+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:16:12.184506+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:16:12.238854+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:16:12.266211+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:16:12.270828+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:16:12.277869+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:16:12.283060+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:16:12.287732+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:16:12.369180+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:16:12.376761+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:16:12.383961+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:16:12.426854+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:16:12.432934+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:16:12.437163+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:16:12.443868+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:16:12.448903+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:16:12.454081+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:16:12.482387+00:00] doctrine.DEBUG: ALTER TABLE `group` DROP FOREIGN KEY FK_6DC044C5A76ED395 [] []
[2019-12-10T13:16:12.497401+00:00] doctrine.DEBUG: DROP INDEX IDX_6DC044C5A76ED395 ON `group` [] []
[2019-12-10T13:16:12.516922+00:00] doctrine.DEBUG: ALTER TABLE `group` DROP user_id, CHANGE name name VARCHAR(255) DEFAULT NULL [] []
[2019-12-10T13:16:12.554628+00:00] doctrine.DEBUG: ALTER TABLE user CHANGE surname surname VARCHAR(255) DEFAULT NULL, CHANGE phone group_id_id INT DEFAULT NULL [] []
[2019-12-10T13:16:12.593026+00:00] doctrine.DEBUG: ALTER TABLE user ADD CONSTRAINT FK_8D93D6492F68B530 FOREIGN KEY (group_id_id) REFERENCES `group` (id) [] []
[2019-12-10T13:16:12.647590+00:00] doctrine.DEBUG: CREATE INDEX IDX_8D93D6492F68B530 ON user (group_id_id) [] []
[2019-12-10T13:18:16.094919+00:00] request.INFO: Matched route "group_index". {"route":"group_index","route_parameters":{"_route":"group_index","_controller":"App\\Controller\\GroupController::index"},"request_uri":"http://symfony.localhost/group/","method":"GET"} []
[2019-12-10T13:18:16.600163+00:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.name AS name_2 FROM group t0 [] []
[2019-12-10T13:18:16.759456+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2 FROM group t0':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group t0' at line 1" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.name AS name_2 FROM group t0':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group t0' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group t0' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80)\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group t0' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []
[2019-12-10T13:18:17.718126+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T13:18:38.121224+00:00] request.INFO: Matched route "group_new". {"route":"group_new","route_parameters":{"_route":"group_new","_controller":"App\\Controller\\GroupController::new"},"request_uri":"http://symfony.localhost/group/new","method":"GET"} []
[2019-12-10T13:18:39.989235+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T13:18:40.728491+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"4fdf6d"},"request_uri":"http://symfony.localhost/_wdt/4fdf6d","method":"GET"} []
[2019-12-10T13:18:44.172762+00:00] request.INFO: Matched route "group_new". {"route":"group_new","route_parameters":{"_route":"group_new","_controller":"App\\Controller\\GroupController::new"},"request_uri":"http://symfony.localhost/group/new","method":"POST"} []
[2019-12-10T13:18:44.214086+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-10T13:18:46.096402+00:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-12-10T13:18:46.122607+00:00] doctrine.DEBUG: INSERT INTO group (name) VALUES (?) {"1":"deneme"} []
[2019-12-10T13:18:46.132617+00:00] doctrine.DEBUG: "ROLLBACK" [] []
[2019-12-10T13:18:46.167384+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'INSERT INTO group (name) VALUES (?)' with params ["deneme"]:  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (name) VALUES ('deneme')' at line 1" at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'INSERT INTO group (name) VALUES (?)' with params [\"deneme\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (name) VALUES ('deneme')' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (name) VALUES ('deneme')' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123)\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group (name) VALUES ('deneme')' at line 1 at /var/www/symfony/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
[2019-12-10T13:18:48.169074+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"fd787e"},"request_uri":"http://symfony.localhost/_wdt/fd787e","method":"GET"} []
[2019-12-10T13:32:03.695593+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:32:03.722201+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:32:03.760090+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:32:03.772147+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:32:03.813773+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:32:03.824308+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:32:03.833814+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:32:03.913888+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:32:03.928803+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:32:04.044077+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-10T13:32:04.051839+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'group' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:32:04.058202+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'group' */ WHERE k.table_name = 'group' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:32:04.063724+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'group' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:32:04.068584+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'group' [] []
[2019-12-10T13:32:04.077558+00:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'symfony' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2019-12-10T13:32:04.097960+00:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'symfony' /*!50116 AND c.constraint_schema = 'symfony' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2019-12-10T13:32:04.168606+00:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'symfony' ORDER BY SEQ_IN_INDEX ASC [] []
[2019-12-10T13:32:04.179371+00:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2019-12-10T13:32:04.239428+00:00] doctrine.DEBUG: CREATE TABLE publishers (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:32:04.287483+00:00] doctrine.DEBUG: CREATE TABLE books (id INT AUTO_INCREMENT NOT NULL, book_id_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, publish_date DATE DEFAULT NULL, count_pages INT DEFAULT NULL, INDEX IDX_4A1B2A9271868B2E (book_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:32:04.321658+00:00] doctrine.DEBUG: CREATE TABLE writers_books (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:32:04.349510+00:00] doctrine.DEBUG: CREATE TABLE writers (id INT AUTO_INCREMENT NOT NULL, writers_books_id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, surname VARCHAR(255) DEFAULT NULL, INDEX IDX_182F8DDF86E83E20 (writers_books_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2019-12-10T13:32:04.398598+00:00] doctrine.DEBUG: ALTER TABLE books ADD CONSTRAINT FK_4A1B2A9271868B2E FOREIGN KEY (book_id_id) REFERENCES writers_books (id) [] []
[2019-12-10T13:32:04.513863+00:00] doctrine.DEBUG: ALTER TABLE writers ADD CONSTRAINT FK_182F8DDF86E83E20 FOREIGN KEY (writers_books_id) REFERENCES writers_books (id) [] []
[2019-12-10T13:32:20.306289+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-10T13:32:20.468637+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-11T06:52:17.842333+00:00] request.INFO: Matched route "default". {"route":"default","route_parameters":{"_route":"default","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://symfony.localhost/default","method":"GET"} []
[2019-12-11T06:52:18.668313+00:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-12-11T06:52:20.253368+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"088fe1"},"request_uri":"http://symfony.localhost/_wdt/088fe1","method":"GET"} []
[2019-12-11T06:52:20.467441+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://symfony.localhost/default")" at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://symfony.localhost/default\") at /var/www/symfony/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /var/www/symfony/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2019-12-11T06:59:12.977083+00:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2019-12-11T06:59:13.200312+00:00] doctrine.DEBUG: CREATE TABLE migration_versions (version VARCHAR(14) NOT NULL, executed_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', PRIMARY KEY(version)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
